# Specifications.
t_step: 0.8
security_margin: [0.09, 0.05]
left_foot_convex_hull: [-0.28, 0.2,
		        -0.20, 0.3, 
		         0.00, 0.4, 
		         0.20, 0.3, 
		         0.28, 0.2]
right_foot_convex_hull: [-0.28, -0.2,
		         -0.20, -0.3, 
		          0.00, -0.4, 
		          0.20, -0.3, 
		          0.28, -0.2]
foot_width: 0.1380
foot_length: 0.2172
foot_distance: 0.2

# Interpolation.
command_period: 0.005
n_still: 10
t_ds: 0.1
step_height: 0.05

# Initial values.
com_x: [0.00949035, 0.0, 0.0]
com_y: [0.095,      0.0, 0.0]
com_z: 0.814
com_q: [0.0 , 0.0, 0.0]
support_foot: left
foot_x: 0.00949035
foot_y: 0.095
foot_q: 0.0

# Environment.
gravity: 9.81

# Obstacle.
x_pos:  10
y_pos:  10
radius: 0

# Optimization.
n: 16
t: 0.1	
alpha: 1
beta: 1e-6
gamma: 1e-5
cpu_time: 0.01
nwsr: 100
